### ISSUE TITLE
Develop a Linux Ubuntu package for Launchpad

### ISSUE THREAD

**Issue by alyeffy** [bioSyntax/bioSyntax#21]
[Launchpad](https://launchpad.net/ubuntu) is a software collaboration platform that has a large Ubuntu project community where people can create, host, and use other Ubuntu packages, as well as report and fix and bugs along the way. Putting together a bioSyntax package on Launchpad will make the installation process for Linux Ubuntu systems a lot easier, especially for the less/gedit text editors.
A guide to creating an Ubuntu package can be found [here](http://packaging.ubuntu.com/html/packaging-new-software.html).

**Comment by Dybian** [comment]
Hi,
I started to package bioSyntax for the [Debian Med project](https://wiki.debian.org/DebianMed). It works for gedit but it needs more work for less.

**Comment by ababaian** [comment]
That's awesome @Dybian!

If you run into any problems please let me know, I've been trying to streamline the less installation for a while. I'll update the instructions on the website tonight but I've managed to have all the biosyntax specific files be installed in the users home folder as opposed to in the source-highlight folder which requires sudo permissions. I would love to help in any way.

**Comment by Dybian** [comment]
Hi,

I created a repository for the package development here [1]. If you
want to be involved you are more than welcome :-) you just need to
create an account on Salsa (our GitLab instance) and have a look to
our team policy [2]. It is always better when upstream devs are
involved in packaging because they know the software better than
maintainers.

The package installs biosyntax at the system-level (so in
/usr/share/...) after which users still need to activate plugins for
themselves. I probably need to write a README file to explain how
activated the different plugins.
I think the package is in good shape, I still need to test it before
to push it in official repository.

Best,
Dylan

[1] https://salsa.debian.org/med-team/biosyntax
[2] https://debian-med.alioth.debian.org/docs/policy.html

**Comment by Dybian** [comment]
The package is almost ready except that I just remarked the tarball from https://github.com/bioSyntax/bioSyntax/archive/v0.1-beta4.tar.gz contain an empty vim folder. Is it possible to fix that to allow me to finish the package for the vim plugin.

**Comment by ababaian** [comment]
So this is a quirk of github, since the vim package is itself a sub-module of the bioSyntax-vim repo, you need to use the `https://github.com/bioSyntax/bioSyntax/releases/download/v0.1-beta4/bioSyntax-0.1.beta4.zip` download link which is packaged to contain all 4 bioSyntax sets.

The auto-generated package on github doesn't do submodules be default and there's no way to change that behavior so we don't use it for anything (also you can't track download stats on it).

**Comment by Dybian** [comment]
Hi,
Some news, the package is in the Debian NEW queue [1], it will be verified
by a FTP master before to go into official Debian repository. This step can
take some hours up to some months, depending of FTP master availability.
Once accepted it will be propagated to derived Debian distributions (e.g.
Ubuntu and so on). This is probably too late for the next Ubuntu LTS, but
it is still possible to push biosyntax into backports repositories [2].
Another possibility, is to create a biosyntax PPA [3] to distribute
biosyntax for still supported Ubuntu versions.

Best,
Dylan


[1] https://ftp-master.debian.org/new.html
[2] https://help.ubuntu.com/community/UbuntuBackports
[3] https://help.launchpad.net/Packaging/PPA

**Comment by alyeffy** [comment]
Hi @Dybian,
Thank you so much for doing all of this. I think option 3 would be the best at this point so that it's at least available for use as soon as possible. Would you mind spearheading that as well? We'd really appreciate it :)

**Comment by Dybian** [comment]
Hi,

I created the bioSyntax team on launchpad [1]. Could someone from the team
asks to join the team on launchpad, I will give the admin rights. I will
push first packages for still maintained LTS Ubuntu versions but I will not
be able to maintain this PPA for long term. I can explain you how to push
new versions, it is quite easy ;-).

Best,
Dylan

[1] https://launchpad.net/~biosyntax

>

**Comment by ababaian** [comment]
Sweet thanks Dybian! @alyeffy you got this or do I?

**Comment by alyeffy** [comment]
@Dybian Thanks, I've requested to join!

**Comment by Dybian** [comment]
The PPA contains packages for Bionic, Artful, Xenial, and Trusty. I was unable to test them, so reports are welcome.

**Comment by Dybian** [comment]
Biosyntax is now officially part of [Debian](https://tracker.debian.org/pkg/biosyntax) and [Ubuntu](https://launchpad.net/ubuntu/+source/biosyntax).
Once a non-beta version will be release I will try to push it in backport repositories.
