### ISSUE TITLE
Port to VSCode

### ISSUE THREAD

**Issue by alyeffy** [bioSyntax/bioSyntax#32]
By popular request from [/r/bioinformatics](https://www.reddit.com/r/bioinformatics/comments/8bo5f2/would_appreciate_your_feedback/)! Don't use it personally but I know quite a few people who do. It's available for [all platforms](https://code.visualstudio.com/) as well and there are some [guidelines](https://gcthesoftwareengineer.com/2017/01/how-to-create-custom-syntax-highlighting-in-a-visual-studio-code-extension/) to get started, so it's definitely worth pursuing.

**Comment by ababaian** [comment]
@liyao001 I've gone through the VSCode and it looks/feels exactly like the sublime version which is great! The only thing I can think of that would be really sweet is automatic switching to the bioSyntax theme when a file with the appropriate file extension is loaded. i.e. For normal code you're using say Solarized, then if you open a fasta file it auto-detects it and switches to bioSyntax. Not sure if that's available in VScode like it is in Sublime but worth looking into.

Also would you be willing to write few hundred words to outline how to develop for VSCode like [here](https://biosyntax.org/dev) to keep the documentation complete?

**Comment by liyao001** [comment]
Ok, I'll try both of the two things in the next couple of days~

**Comment by ababaian** [comment]
That's great! I found that even before I installed bioSyntax in VSCode and opened a `sam` file it 'suggested' bioSyntax as a package to install. Then I would click yes it would install and the coloring looked strange because it wasn't the correct theme and there was no documentation which suggested this was anything but the intended coloring scheme. Like this I think it's all much more seamless. Great work man! The VSCode package is getting very popular, I think because it's the suggested add-on when people use bio formats in VSCode. :) :+1:
